language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"


matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install Cython 
  - pip install ripser
  - pip install .
  - pip install pytest-cov

script:
  - pytest --cov persim

after_success:
  - bash <(curl -s https://codecov.io/bash)
